name: Deploying to MASTER

on:
  push:
    branches: [master] # the branch we want this to run on
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: false
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Node setup
        uses: actions/setup-node@v1
        with:
          node-version: 17

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIA6DLTTUKQVQJ3A25Z
          aws-secret-access-key: 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
          aws-region: eu-west-2

      - name: yarn install
        run: yarn

      - name: build
        run: yarn build

      - name: copy files to s3
        run: aws s3 sync ./build s3://werdevs-asker

      - name: Invalidate cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E25SWK3D42KGMU \
            --paths "/*"

      - name: notification about deploy
        uses: appleboy/telegram-action@master
        with:
          to: -426080489
          token: 1218175611:AAH1gQvMw7H9LsfCoBKxIetwq1O9jGOzvS0
          args: ASKER deploying status is "${{ job.status }}".